/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as QuickNoteImport } from "./routes/quick-note"
import { Route as AiImport } from "./routes/ai"
import { Route as AppRootImport } from "./routes/_appRoot"
import { Route as AppRootIndexImport } from "./routes/_appRoot.index"
import { Route as ShareGistIdImport } from "./routes/share.$gistId"
import { Route as AppRootTasksImport } from "./routes/_appRoot.tasks"
import { Route as AppRootSettingsImport } from "./routes/_appRoot.settings"
import { Route as AppRootProjectsImport } from "./routes/_appRoot.projects"
import { Route as AppRootPeopleImport } from "./routes/_appRoot.people"
import { Route as AppRootLinksImport } from "./routes/_appRoot.links"
import { Route as AppRootInboxImport } from "./routes/_appRoot.inbox"
import { Route as AppRootFileImport } from "./routes/_appRoot.file"
import { Route as AppRootTagsIndexImport } from "./routes/_appRoot.tags.index"
import { Route as AppRootNotesIndexImport } from "./routes/_appRoot.notes.index"
import { Route as AppRootTagsSplatImport } from "./routes/_appRoot.tags_.$"
import { Route as AppRootNotesSplatImport } from "./routes/_appRoot.notes_.$"

// Create/Update Routes

const QuickNoteRoute = QuickNoteImport.update({
  id: "/quick-note",
  path: "/quick-note",
  getParentRoute: () => rootRoute,
} as any)

const AiRoute = AiImport.update({
  id: "/ai",
  path: "/ai",
  getParentRoute: () => rootRoute,
} as any)

const AppRootRoute = AppRootImport.update({
  id: "/_appRoot",
  getParentRoute: () => rootRoute,
} as any)

const AppRootIndexRoute = AppRootIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRootRoute,
} as any)

const ShareGistIdRoute = ShareGistIdImport.update({
  id: "/share/$gistId",
  path: "/share/$gistId",
  getParentRoute: () => rootRoute,
} as any)

const AppRootTasksRoute = AppRootTasksImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootSettingsRoute = AppRootSettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootProjectsRoute = AppRootProjectsImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootPeopleRoute = AppRootPeopleImport.update({
  id: "/people",
  path: "/people",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootLinksRoute = AppRootLinksImport.update({
  id: "/links",
  path: "/links",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootInboxRoute = AppRootInboxImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootFileRoute = AppRootFileImport.update({
  id: "/file",
  path: "/file",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootTagsIndexRoute = AppRootTagsIndexImport.update({
  id: "/tags/",
  path: "/tags/",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootNotesIndexRoute = AppRootNotesIndexImport.update({
  id: "/notes/",
  path: "/notes/",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootTagsSplatRoute = AppRootTagsSplatImport.update({
  id: "/tags_/$",
  path: "/tags/$",
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootNotesSplatRoute = AppRootNotesSplatImport.update({
  id: "/notes_/$",
  path: "/notes/$",
  getParentRoute: () => AppRootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_appRoot": {
      id: "/_appRoot"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AppRootImport
      parentRoute: typeof rootRoute
    }
    "/ai": {
      id: "/ai"
      path: "/ai"
      fullPath: "/ai"
      preLoaderRoute: typeof AiImport
      parentRoute: typeof rootRoute
    }
    "/quick-note": {
      id: "/quick-note"
      path: "/quick-note"
      fullPath: "/quick-note"
      preLoaderRoute: typeof QuickNoteImport
      parentRoute: typeof rootRoute
    }
    "/_appRoot/file": {
      id: "/_appRoot/file"
      path: "/file"
      fullPath: "/file"
      preLoaderRoute: typeof AppRootFileImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/inbox": {
      id: "/_appRoot/inbox"
      path: "/inbox"
      fullPath: "/inbox"
      preLoaderRoute: typeof AppRootInboxImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/links": {
      id: "/_appRoot/links"
      path: "/links"
      fullPath: "/links"
      preLoaderRoute: typeof AppRootLinksImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/people": {
      id: "/_appRoot/people"
      path: "/people"
      fullPath: "/people"
      preLoaderRoute: typeof AppRootPeopleImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/projects": {
      id: "/_appRoot/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof AppRootProjectsImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/settings": {
      id: "/_appRoot/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppRootSettingsImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/tasks": {
      id: "/_appRoot/tasks"
      path: "/tasks"
      fullPath: "/tasks"
      preLoaderRoute: typeof AppRootTasksImport
      parentRoute: typeof AppRootImport
    }
    "/share/$gistId": {
      id: "/share/$gistId"
      path: "/share/$gistId"
      fullPath: "/share/$gistId"
      preLoaderRoute: typeof ShareGistIdImport
      parentRoute: typeof rootRoute
    }
    "/_appRoot/": {
      id: "/_appRoot/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppRootIndexImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/notes_/$": {
      id: "/_appRoot/notes_/$"
      path: "/notes/$"
      fullPath: "/notes/$"
      preLoaderRoute: typeof AppRootNotesSplatImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/tags_/$": {
      id: "/_appRoot/tags_/$"
      path: "/tags/$"
      fullPath: "/tags/$"
      preLoaderRoute: typeof AppRootTagsSplatImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/notes/": {
      id: "/_appRoot/notes/"
      path: "/notes"
      fullPath: "/notes"
      preLoaderRoute: typeof AppRootNotesIndexImport
      parentRoute: typeof AppRootImport
    }
    "/_appRoot/tags/": {
      id: "/_appRoot/tags/"
      path: "/tags"
      fullPath: "/tags"
      preLoaderRoute: typeof AppRootTagsIndexImport
      parentRoute: typeof AppRootImport
    }
  }
}

// Create and export the route tree

interface AppRootRouteChildren {
  AppRootFileRoute: typeof AppRootFileRoute
  AppRootInboxRoute: typeof AppRootInboxRoute
  AppRootLinksRoute: typeof AppRootLinksRoute
  AppRootPeopleRoute: typeof AppRootPeopleRoute
  AppRootProjectsRoute: typeof AppRootProjectsRoute
  AppRootSettingsRoute: typeof AppRootSettingsRoute
  AppRootTasksRoute: typeof AppRootTasksRoute
  AppRootIndexRoute: typeof AppRootIndexRoute
  AppRootNotesSplatRoute: typeof AppRootNotesSplatRoute
  AppRootTagsSplatRoute: typeof AppRootTagsSplatRoute
  AppRootNotesIndexRoute: typeof AppRootNotesIndexRoute
  AppRootTagsIndexRoute: typeof AppRootTagsIndexRoute
}

const AppRootRouteChildren: AppRootRouteChildren = {
  AppRootFileRoute: AppRootFileRoute,
  AppRootInboxRoute: AppRootInboxRoute,
  AppRootLinksRoute: AppRootLinksRoute,
  AppRootPeopleRoute: AppRootPeopleRoute,
  AppRootProjectsRoute: AppRootProjectsRoute,
  AppRootSettingsRoute: AppRootSettingsRoute,
  AppRootTasksRoute: AppRootTasksRoute,
  AppRootIndexRoute: AppRootIndexRoute,
  AppRootNotesSplatRoute: AppRootNotesSplatRoute,
  AppRootTagsSplatRoute: AppRootTagsSplatRoute,
  AppRootNotesIndexRoute: AppRootNotesIndexRoute,
  AppRootTagsIndexRoute: AppRootTagsIndexRoute,
}

const AppRootRouteWithChildren = AppRootRoute._addFileChildren(AppRootRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof AppRootRouteWithChildren
  "/ai": typeof AiRoute
  "/quick-note": typeof QuickNoteRoute
  "/file": typeof AppRootFileRoute
  "/inbox": typeof AppRootInboxRoute
  "/links": typeof AppRootLinksRoute
  "/people": typeof AppRootPeopleRoute
  "/projects": typeof AppRootProjectsRoute
  "/settings": typeof AppRootSettingsRoute
  "/tasks": typeof AppRootTasksRoute
  "/share/$gistId": typeof ShareGistIdRoute
  "/": typeof AppRootIndexRoute
  "/notes/$": typeof AppRootNotesSplatRoute
  "/tags/$": typeof AppRootTagsSplatRoute
  "/notes": typeof AppRootNotesIndexRoute
  "/tags": typeof AppRootTagsIndexRoute
}

export interface FileRoutesByTo {
  "/ai": typeof AiRoute
  "/quick-note": typeof QuickNoteRoute
  "/file": typeof AppRootFileRoute
  "/inbox": typeof AppRootInboxRoute
  "/links": typeof AppRootLinksRoute
  "/people": typeof AppRootPeopleRoute
  "/projects": typeof AppRootProjectsRoute
  "/settings": typeof AppRootSettingsRoute
  "/tasks": typeof AppRootTasksRoute
  "/share/$gistId": typeof ShareGistIdRoute
  "/": typeof AppRootIndexRoute
  "/notes/$": typeof AppRootNotesSplatRoute
  "/tags/$": typeof AppRootTagsSplatRoute
  "/notes": typeof AppRootNotesIndexRoute
  "/tags": typeof AppRootTagsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_appRoot": typeof AppRootRouteWithChildren
  "/ai": typeof AiRoute
  "/quick-note": typeof QuickNoteRoute
  "/_appRoot/file": typeof AppRootFileRoute
  "/_appRoot/inbox": typeof AppRootInboxRoute
  "/_appRoot/links": typeof AppRootLinksRoute
  "/_appRoot/people": typeof AppRootPeopleRoute
  "/_appRoot/projects": typeof AppRootProjectsRoute
  "/_appRoot/settings": typeof AppRootSettingsRoute
  "/_appRoot/tasks": typeof AppRootTasksRoute
  "/share/$gistId": typeof ShareGistIdRoute
  "/_appRoot/": typeof AppRootIndexRoute
  "/_appRoot/notes_/$": typeof AppRootNotesSplatRoute
  "/_appRoot/tags_/$": typeof AppRootTagsSplatRoute
  "/_appRoot/notes/": typeof AppRootNotesIndexRoute
  "/_appRoot/tags/": typeof AppRootTagsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/ai"
    | "/quick-note"
    | "/file"
    | "/inbox"
    | "/links"
    | "/people"
    | "/projects"
    | "/settings"
    | "/tasks"
    | "/share/$gistId"
    | "/"
    | "/notes/$"
    | "/tags/$"
    | "/notes"
    | "/tags"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/ai"
    | "/quick-note"
    | "/file"
    | "/inbox"
    | "/links"
    | "/people"
    | "/projects"
    | "/settings"
    | "/tasks"
    | "/share/$gistId"
    | "/"
    | "/notes/$"
    | "/tags/$"
    | "/notes"
    | "/tags"
  id:
    | "__root__"
    | "/_appRoot"
    | "/ai"
    | "/quick-note"
    | "/_appRoot/file"
    | "/_appRoot/inbox"
    | "/_appRoot/links"
    | "/_appRoot/people"
    | "/_appRoot/projects"
    | "/_appRoot/settings"
    | "/_appRoot/tasks"
    | "/share/$gistId"
    | "/_appRoot/"
    | "/_appRoot/notes_/$"
    | "/_appRoot/tags_/$"
    | "/_appRoot/notes/"
    | "/_appRoot/tags/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRootRoute: typeof AppRootRouteWithChildren
  AiRoute: typeof AiRoute
  QuickNoteRoute: typeof QuickNoteRoute
  ShareGistIdRoute: typeof ShareGistIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRootRoute: AppRootRouteWithChildren,
  AiRoute: AiRoute,
  QuickNoteRoute: QuickNoteRoute,
  ShareGistIdRoute: ShareGistIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_appRoot",
        "/ai",
        "/quick-note",
        "/share/$gistId"
      ]
    },
    "/_appRoot": {
      "filePath": "_appRoot.tsx",
      "children": [
        "/_appRoot/file",
        "/_appRoot/inbox",
        "/_appRoot/links",
        "/_appRoot/people",
        "/_appRoot/projects",
        "/_appRoot/settings",
        "/_appRoot/tasks",
        "/_appRoot/",
        "/_appRoot/notes_/$",
        "/_appRoot/tags_/$",
        "/_appRoot/notes/",
        "/_appRoot/tags/"
      ]
    },
    "/ai": {
      "filePath": "ai.tsx"
    },
    "/quick-note": {
      "filePath": "quick-note.tsx"
    },
    "/_appRoot/file": {
      "filePath": "_appRoot.file.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/inbox": {
      "filePath": "_appRoot.inbox.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/links": {
      "filePath": "_appRoot.links.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/people": {
      "filePath": "_appRoot.people.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/projects": {
      "filePath": "_appRoot.projects.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/settings": {
      "filePath": "_appRoot.settings.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/tasks": {
      "filePath": "_appRoot.tasks.tsx",
      "parent": "/_appRoot"
    },
    "/share/$gistId": {
      "filePath": "share.$gistId.tsx"
    },
    "/_appRoot/": {
      "filePath": "_appRoot.index.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/notes_/$": {
      "filePath": "_appRoot.notes_.$.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/tags_/$": {
      "filePath": "_appRoot.tags_.$.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/notes/": {
      "filePath": "_appRoot.notes.index.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/tags/": {
      "filePath": "_appRoot.tags.index.tsx",
      "parent": "/_appRoot"
    }
  }
}
ROUTE_MANIFEST_END */
